services:
  statify:
    build:
      context: .
      args:
        VITE_SPOTIFY_CLIENT_ID: ${VITE_SPOTIFY_CLIENT_ID}
    container_name: statify
    ports:
      - "3010:80"
    restart: unless-stopped
